name: Create AWS S3 Bucket

on: 
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Name of the S3 Bucket'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform Apply
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan and apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./roots/bucket
          backend_config: |
            bucket=ileri-tf-state
            key=tfstate
            region=eu-central-1
          auto_approve: true
          variables: |
            bucket_name = "${{ inputs.bucket }}"
            
