name: Create AWS ECR Repository

on: 
  workflow_dispatch:
    inputs:
      ecr:
        description: 'Name of the ECR Repository'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform Apply
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-apply@v1
        with:
          path: ./roots/ecr
          backend_config_file: backend.tfvars.ghactions
          auto_approve: true
          variables: |
            repository_name = "${{ inputs.ecr }}"
