name: Create terraform plan

on: 
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Name of the S3 Bucket'
        required: true
        type: string
      ecr:
        description: 'Name of the ECR Repository'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for the terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./
          variables: |
            bucket_name = "${{ inputs.bucket }}"
            repository_name = "${{ inputs.ecr }}"
