name: Terraform Plan

on: 
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan - S3 Bucket
        uses: dflook/terraform-plan@v1
        with:
          path: ./roots/bucket
          backend_config_file: ./backend.tfvars.ghactions
          variables: |
            bucket_name = "ghactions-test-${{ github.sha }}"

      - name: terraform plan - ECR Repo
        uses: dflook/terraform-plan@v1
        with:
          path: ./roots/ecr
          backend_config_file: ./backend.tfvars.ghactions
          variables: |
            repository_name = "ghactions-test-${{ github.sha }}"
